/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        primary: {
          DEFAULT: 'var(--accent-blue)',
          50: 'var(--accent-blue-50, #eff6ff)',
          100: 'var(--accent-blue-100, #bfdbfe)',
          200: 'var(--accent-blue-200, #93c5fd)',
          300: 'var(--accent-blue-300, #60a5fa)',
          400: 'var(--accent-blue-400, #2563eb)',
          500: 'var(--accent-blue-500, #3b82f6)',
          600: 'var(--accent-blue-600, #2563eb)',
          700: 'var(--accent-blue-700, #1d4ed8)',
          800: 'var(--accent-blue-800, #1e40af)',
          900: 'var(--accent-blue-900, #1e40af)',
        },
        secondary: {
          DEFAULT: 'var(--accent-purple)',
          50: 'var(--accent-purple-50, #faf5ff)',
          100: 'var(--accent-purple-100, #e9d8fd)',
          200: 'var(--accent-purple-200, #d8bcfe)',
          300: 'var(--accent-purple-300, #c084fc)',
          400: 'var(--accent-purple-400, #a855f7)',
          500: 'var(--accent-purple-500, #8b5cf6)',
          600: 'var(--accent-purple-600, #7c3aed)',
          700: 'var(--accent-purple-700, #6d28d9)',
          800: 'var(--accent-purple-800, #5b21b6)',
          900: 'var(--accent-purple-900, #5b21b6)',
        },
        accent: {
          teal: {
            DEFAULT: 'var(--accent-teal)',
            50: 'var(--accent-teal-50, #ecfdf5)',
            100: 'var(--accent-teal-100, #d1fae5)',
            200: 'var(--accent-teal-200, #a7f3d0)',
            300: 'var(--accent-teal-300, #67e8f9)',
            400: 'var(--accent-teal-400, #22c55e)',
            500: 'var(--accent-teal-500, #14b8a6)',
            600: 'var(--accent-teal-600, #0d9488)',
            700: 'var(--accent-teal-700, #0f766e)',
            800: 'var(--accent-teal-800, #10b981)',
            900: 'var(--accent-teal-900, #14b8a6)',
          },
          green: {
            DEFAULT: 'var(--accent-green)',
            50: 'var(--accent-green-50, #ecfdf3)',
            100: 'var(--accent-green-100, #d1fae5)',
            200: 'var(--accent-green-200, #a3f7c6)',
            300: 'var(--accent-green-300, #86efac)',
            400: 'var(--accent-green-400, #4ade80)',
            500: 'var(--accent-green-500, #22c55e)',
            600: 'var(--accent-green-600, #16a34a)',
            700: 'var(--accent-green-700, #15803d)',
            800: 'var(--accent-green-800, #16a34a)',
            900: 'var(--accent-green-900, #16a34a)',
          },
          orange: {
            DEFAULT: 'var(--accent-orange)',
            50: 'var(--accent-orange-50, #fff7ed)',
            100: 'var(--accent-orange-100, #ffedd5)',
            200: 'var(--accent-orange-200, #fed7aa)',
            300: 'var(--accent-orange-300, #fdba9e)',
            400: 'var(--accent-orange-400, #fb923c)',
            500: 'var(--accent-orange-500, #f97316)',
            600: 'var(--accent-orange-600, #ea580c)',
            700: 'var(--accent-orange-700, #c2410c)',
            800: 'var(--accent-orange-800, #9a3412)',
            900: 'var(--accent-orange-900, #9a3412)',
          },
        },
        destructive: {
          DEFAULT: 'hsl(0 84.6% 60.2%)',
          foreground: 'hsl(0 0% 98%)',
        },
        muted: {
          DEFAULT: 'var(--text-secondary)',
          foreground: 'var(--text-muted)',
        },
        accent: {
          blue: 'var(--accent-blue)',
          purple: 'var(--accent-purple)',
          teal: 'var(--accent-teal)',
          green: 'var(--accent-green)',
          orange: 'var(--accent-orange)',
        },
        risk: {
          low: 'var(--risk-low)',
          medium: 'var(--risk-medium)',
          high: 'var(--risk-high)',
          critical: 'var(--risk-critical)',
        },
        entity: {
          vasp: '#3b82f6',
          mixer: '#ef4444',
          bridge: '#f59e0b',
          scam: '#a855f7',
          unknown: 'var(--text-muted)',
        },
        cypher: {
          cyan: '#00f0ff',
          blue: '#3b82f6',
        },
        sidebar: {
          bg: '#0f172a',
          fg: '#f8fafc',
          muted: '#64748b',
          border: '#334155',
        },
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        inner: 'var(--shadow-inset)',
      },
      transitionProperty: {
        DEFAULT: 'var(--transition-fast)',
        fast: 'var(--transition-fast)',
        normal: 'var(--transition-normal)',
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
}